# Generated by Django 4.2.13 on 2024-07-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simple', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='locatin',
            new_name='location',
        ),
    ]
